name: Deploy Website

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '21.2.0' # Choose the Node.js version suitable for your project

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: List output directory
        run: ls -R build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          ftp-server: ftp://${{ secrets.FTP_SERVER }}/
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          git-ftp-args: --insecure # Remove --insecure if your FTP server supports secure connections

